// <auto-generated />
using System;
using EmployeeService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmployeeService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528174619_CreateEmployeeServiceTable")]
    partial class CreateEmployeeServiceTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmployeeService.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = "usr-mgr-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mgr@gmail.com",
                            Name = "Mini",
                            Role = "Manager"
                        },
                        new
                        {
                            EmployeeId = "usr-emp-001",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "memp@gmail.com",
                            ManagerId = "usr-mgr-001",
                            Name = "Arav",
                            Role = "Emp"
                        });
                });

            modelBuilder.Entity("EmployeeService.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalAllocated")
                        .HasColumnType("integer");

                    b.Property<int>("Used")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = "usr-mgr-001",
                            LeaveType = "Casual",
                            TotalAllocated = 15,
                            Used = 0
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = "usr-mgr-001",
                            LeaveType = "Sick",
                            TotalAllocated = 15,
                            Used = 0
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = "usr-mgr-001",
                            LeaveType = "Privilege",
                            TotalAllocated = 15,
                            Used = 0
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = "usr-emp-001",
                            LeaveType = "Casual",
                            TotalAllocated = 15,
                            Used = 0
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = "usr-emp-001",
                            LeaveType = "Sick",
                            TotalAllocated = 15,
                            Used = 0
                        },
                        new
                        {
                            Id = 6,
                            EmployeeId = "usr-emp-001",
                            LeaveType = "Privilege",
                            TotalAllocated = 15,
                            Used = 0
                        });
                });

            modelBuilder.Entity("EmployeeService.Models.LeaveBalance", b =>
                {
                    b.HasOne("EmployeeService.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
