// <auto-generated />
using IdentityService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526174516_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "usr-mgr-001",
                            Email = "mgr@gmail.com",
                            Name = "Mini",
                            PasswordHash = "$2a$11$VdR7EKaWiS0o/V1Sht9nyOWOfuTv1F6PVJv1eDRZpqhqPFKCCuoC2",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = "usr-emp-001",
                            Email = "memp@gmail.com",
                            ManagerId = "usr-mgr-001",
                            Name = "Arav",
                            PasswordHash = "$2a$11$aVCuiuIznRADv0n3nhaGaOeSfetYMJvwnDoVjCCu/GG0iRh6bf2yK",
                            Role = "Emp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
