// <auto-generated />
using IdentityService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdentityService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdentityService.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "usr-mgr-001",
                            Email = "mgr@gmail.com",
                            Name = "Mini",
                            PasswordHash = "$2a$11$ddxDB93dEXdHWJuz6uNLoOQFQMTTk9ebSuoahM8AOOMIa5iIhOhdi",
                            Role = "Manager"
                        },
                        new
                        {
                            UserId = "usr-emp-001",
                            Email = "memp@gmail.com",
                            ManagerId = "usr-mgr-001",
                            Name = "Arav",
                            PasswordHash = "$2a$11$n68rB4cpeBO5fKMf9J3/r.GeAembomFybQw60iN03noL/mk9TkVa6",
                            Role = "Emp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
